### ISSUE TITLE
Bash on Ubuntu 16.04.2 LTS doesn't appear to support `read -s` commands in installation.sh

### ISSUE THREAD

**Issue by msmollin** [Mordreak/FactorioWebView#1]
Tried installing this today on a fully updated but otherwise vanilla Ubuntu 16.04.2 LTS box, and got stuck at `installation.sh: 41: read: Illegal option -s` which kinda floored me that Ubuntu's Bash would have issues with that. I can't seem to find anything referencing the issue either given anecdotal googling.

Removing the `-s` and allowing it to echo my passwords to the shell allowed the install to proceed without issue. Any thoughts as to what this might be? I was SSH'd into the box but I can't imagine that having something to do with it, would it?

**Comment by Mordreak** [comment]
Well I made a mistake in the Readme, you should run the installer with bash and not sh which does not support options on read and echo, try something like "sudo bash installation.sh". It should Work ;)
